### ISSUE TITLE
Using own client_id

### ISSUE THREAD

**Issue by derekfinlinson** [bguidinger/Xrm.ReportRenderer#17]
Awesome solution Bob. I'm using it for a client and would prefer using an app registration in their Azure AD instead of the client id set in the source. I've registered a Native app and given permissions to D365 and then authorized the app but get a 401 Unauthorized when getting the access token. The same resource/username/password parameters work fine with your client id in there. Any idea what I might be missing?

Also, I tried switching to using a client id/secret and that gets me an access token just fine but then it fails to get the ReportSession and ControlId.

I can just use your solution as is if necessary but just wanted to check if you knew of any solutions to either of the above.

Thanks.

**Comment by bguidinger** [comment]
@derekfinlinson I ran into your second issue during my testing.  It seems that the access token needs to have an actual user context (i.e. not an application user) in order to successfully render the reports. This is probably because of some internal AD calls that the SSRS servers do.  The downside, of course, is that you have to get an access token with a username/password which is less secure than other OAuth flows.

The Client ID that's hard-coded is actually the same one used by the Plugin Registration Tool, so it was created by Microsoft and lives in their AD tenant.  It's fairly unlikely that it will ever change/be disabled.  Is that why you would prefer to use your own app registration?

I could probably add it as a custom "override" parameter on the plugin registration.  If it's provided, use it...otherwise default to the one from the Plugin Registration Tool.

With that said, I'm not sure why you're getting a 401 when using your own Client ID.  One thing to check would be if you granted admin consent on the API Permissions tab of the app registration.  If I remember right that is necessary since the user doesn't get the popup asking them to consent (as  you would in a traditional implicit OAuth flow).

**Comment by derekfinlinson** [comment]
Thanks @bguidinger that all makes sense. I was concerned something may happen to the client id but since it's from MS i'm sure it's safe to use.
