### ISSUE TITLE
Adding a rendered report to Timeline

### ISSUE THREAD

**Issue by dpekarchik** [bguidinger/Xrm.ReportRenderer#47]
Does anyone know a way to take a rendered pdf report and add it to the timeline in dynamics? When I go to create a record it does not allow me to select output like it does in send an email

**Comment by bguidinger** [comment]
@dpekarchik You should be able to create an "annotation" record (i.e. a note) and attach the file.

**Comment by sureshkumarsatti** [comment]
Hello @bguidinger ,

I wanted to achieve something similar and whenever i create a note attachment i get this error "Invalid character in field 'documentbody': '', hexadecimal value 0x12, is an invalid character.". I thought the issue was with the output from the report rendered itself, but when i tried to create a file on sharepoint using the same output, it worked fine. Just wondering what might be the possible issue here.
