### ISSUE TITLE
(400) Bad Request starting on 2/22

### ISSUE THREAD

**Issue by MDrake3** [bguidinger/Xrm.ReportRenderer#58]
Hello,

I have 3 flows set up using the tool that have been running successfully for months.  All three started to fail on 2/22 with the error "Bad Request".  code: "0x80040265", message: "Something went wrong: The remote server returned an error: (400) Bad Request."

I checked all the setup and it looks to still be correct and valid.  When running the test for the custom connector, all the GET commands and the POST_GetReportParameters return normally without an error.  If I try to test the _POST_RenderReport, it is always returns an error with the same error message.  I've tested built in and custom reports that do not have parameters with the same result.  I've tried PDF, DOC, XLS for format and all give the same result.

Was there a change in CRM that resulted in breaking this?  Or do you have any tips that I could try to fix this?

Thanks!

**Comment by dariomagana10** [comment]
I have the exact same Issue, All of my API calls work but the _POST_RenderReport request. I tried various rendering formats but still won´t work. Did you solve it MDrake?

**Comment by MDrake3** [comment]
I have not been able to resolve it.  Was the API working for you before or are you new to using it?

**Comment by dariomagana10** [comment]
I’m new, I saw the previous issues on github and last year some user posted the same, maybe they’ll fix the bug, for now I”ll create my flows and leave them disactive.

If I ever find a solution or it starts working again, I’ll let you know


Scarica Outlook per iOS<https://aka.ms/o0ukef>
________________________________
Da: MDrake3 ***@***.***>
Inviato: Friday, March 12, 2021 3:36:17 PM
A: bguidinger/Xrm.ReportScheduler ***@***.***>
Cc: Miguel Darío Magaña Heredia ***@***.***>; Comment ***@***.***>
Oggetto: Re: [bguidinger/Xrm.ReportScheduler] (400) Bad Request starting on 2/22 (#58)


I have not been able to resolve it. Was the API working for you before or are you new to using it?

**Comment by kdbeanblossom** [comment]
I have the same problem. This is the first time I have set this up. Everything works except for _POST_RenderReport. Hope this gets resolved because this would be an extremely useful tool for me.

**Comment by dariomagana10** [comment]
Hey guys, I fixed the problem, first I disabled the MFA(multifactor authentication) on the Office Admin Portal -> Users -> Active Users -> Multifactor Authentication -> Disable. 

And I checked again the user/password on the Solutions configuration on D365. Advanced Settings -> Solutions -> Render Report(or whatever name you gave it) -> Configuration -> I set a user and password of my organization with admin permissions and that user is also the one creating the Flows. 

Once I changed this and Published all Customizations my Flow worked, I´m still having troubles with the PDF rendering(its sending a huge amount of characters instead of a PDF file) but it works perfectly with HTML5.

Let me know if this helps you

**Comment by kdbeanblossom** [comment]
After disabling MFA and lots of trial and error with passing parameters, I was able to get it to work (even with PDF's), however, once I turned MFA back on, I get the Bad Request error again, which means this won't work with an account with MFA turned on. Does anyone know of a work around for this?

**Comment by bguidinger** [comment]
This solution is no longer being maintained.  Please refer to the updated README for an alternative approach.
